### ISSUE TITLE
Tab deletion moves contents of tab to next file and shifts everything else

### ISSUE THREAD

**Issue by Moosems** [muhammeteminturgut/ttkScrollableNotebook#6]

**Comment by lopuma** [comment]
Could you show more details or an image please to see what happens since I had several errors and now it works correctly.

**Comment by lopuma** [comment]
Ok

**Comment by Moosems** [comment]
> forget does not work properly. The tabs are still there, just hidden. To get this to work properly, I had to destroy the widgets.
> 
> notebookTab's are:
> 
> > .!scrollablenotebook.!notebook2.!frame
> > .!scrollablenotebook.!notebook2.!frame2
> > .!scrollablenotebook.!notebook2.!frame3
> > etc.....
> 
> notebookContent's are:
> 
> > .!frame
> > .!frame2
> > .!frame3
> > etc.....

@Beercow Can you send the code that got this to work?
